baseURL = "https://bopjiang.github.io"
languageCode = "en-us"
title = "江 Blog"
theme = "hugo-ivy"
googleAnalytics = "UA-168084481-1"

[services.disqus]
shortname = 'bopjianggithubio'

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3

[[menu.main]]
    name = "Note"
    url = "/note/"
    weight = 4

[[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 5

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 8
    
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 9

[params]
    description = "Jiang in Thinking"
    footer = "&copy; [bopjiang](https://bopjiang.github.io) 2021 | [Github](https://github.com/bopjiang) | [Twitter](https://twitter.com/bopjiang)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["yaml", "tex", "bash", "go", "python"]
  highlightjsTheme = "github"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true